### ISSUE TITLE
vocabulary not found

### ISSUE THREAD

**Issue by abdallaharioua** [jarobyte91/post_ocr_correction#3]
Hello,

Thank you very much for the published work, it's very interesting.

When trying to use the lib part:

```
# string is the string of characters to correct
    # model is a PyTorch sequence-to-sequence model
    # vocabulary is a correspondence between integers and tokens 
    # (see the preprocessing notebook in the notebooks folder for each language)
    
    from ocr_correction import correct_by_disjoint_window, correct_by_sliding_window
    corrected_string = correct_by_disjoint_window(string, model, vocabulary)
    # or
    corrected_string = correct_by_sliding_window(string, model, vocabulary)
    corrected_string.replace("@", "") # to remove padding character
```

The vocabulary is absent. After checking  the preprocessing notebook (for french language), I noticed that the associated pickles are not uploaded.

Could you please provide the vocabulary so that I can test the approach ?

Thanks in advance,

**Comment by jarobyte91** [comment]
Unfortunately, due to some problems in my lab, I don't have access anymore to my original binary files, but you should be able to reconstruct them by running all the cells from the notebooks one by one. The vocabulary for French is built in the notebook **notebooks/fr/0_exploration.ipynb** in cell 11.
